<?php

require_once "includes/header.php";

!isset($_SESSION['user']) ? header("Location: index.php") : null;

include $appIncludes."navigationbar.php";
?>
<script>
	const PAGE = "<?php echo "homepage" ?>"
</script>




<div id="feed-container">

	<form method="post" action="<?php echo $appControllers."newFeed-controller.php"?>">
		<div id="textarea-container">
			<div id="textarea-controller">
				<textarea name="new-feed" id="new-feed" placeholder="share your thoughts" rows="7" required></textarea>
			</div>
			<div id="feedBtn-controller">
				<div id="media">
					<span class='fas fa-image'></span>
					<span class='fas fa-video'></span>
					<span class='fas fa-microphone'></span>
				</div>
				<button id="feed-btn" type="submit" name="submit" aria-label="submit-feed"><i class="fa fa-paper-plane-o"></i></button>
			</div>
		</div>
	</form>

	<div id="feed-controller">
		<?php
			// get all posts
			// $sql = 'SELECT * FROM "posts" WHERE "parent_id" is Null';
			// // $sql = 'SELECT follow_user_id FROM "follow" WHERE "user_id" = ?'; post of followers
			// $rows = $db->fetch($sql);
										
			// require $appIncludes."feeds.php";

		?>
	</div> <!-- end feed-controller -->

	<div id="loading-container">
		<button id="load-posts">more...</button>
		<div id="loader">
			<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: transparent; display: block; shape-rendering: auto;" width="80px"  height="80px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
				<circle cx="50" cy="50" r="32" stroke-width="5" stroke="#e4560fe8" stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round">
					<animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="2s" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
				</circle>
			</svg><!--[ldio] generated by https://loading.io/ -->
		</div>
	</div>

</div> <!-- end feed-container -->

<?php require_once $appIncludes."footer.php" ?>