<?php
require_once "includes/header.php";
include $appIncludes."navigationbar.php";

!isset($_SESSION['user']) ? header("Location: index.php") : null;
if(isset($_GET["id"])){
	// get user's info
	$sql = "SELECT * FROM `users` WHERE id = ?";
	$params = array($_GET["id"]);
	$row = $db -> row($sql, $params);

	!isset($row->id) ? die("Not found") : null;
	if(isset($_GET['id'])){

		// sql for user's avatar
        $sql = "SELECT * FROM users WHERE id = ?";
        $params = array($_GET['id']);
        $rowUserAvatar = $db->row($sql, $params);
        
        if($rowUserAvatar->avatar){
            $profileAvatar = "<img style='width:100%;height:100%' src='../files/assets/img/avatars/".$row->avatar."' alt='image-profile'>";
        }else{
            $profileAvatar = "<span class='user-icon'>".substr(ucwords($rowUserAvatar->fullname),0,1)."</span>";
        }
    }

}

?>
<script>
	const PAGE = "<?php echo "profile" ?>"
</script>

<div class="profile-container" >	
	<div class="user-container user" data-id="<?php echo $row->id ?>">
		<div class="user">
			<div class="img">
				<?php echo $profileAvatar; ?>
			</div>
			<div class="name">
				<h3><?php echo $row->fullname ?> <small><?php echo "@".$row->username ?></small></h3>
			</div>
			<div class="info">
				<p><span id="followers"><?php echo $row->followers ?></span> followers</p>
				<p><span id="following"><?php echo $row->following ?></span> following</p>
			</div>
		</div>
		<p><?php echo $row->bio ?></p>
		<p id="btn-profile">
			<?php 
				// get follow unfollow btn
				$sql = "SELECT * FROM `follow` WHERE `user_id` = ? AND `follow_user_id` = ?";
				$params = array($_SESSION["user"], $_GET["id"]);
				$rowFollow = $db->row($sql, $params);
				if($rowFollow){
					$follow = "<button class='follow-btn'>unfollow</button>";
				}else{
					$follow = "<button class='follow-btn'>follow</button>";
				}

			echo $_SESSION['user'] === $_GET["id"] ? "<a href='edit.php'>edit</a>" : $follow ?>
		</p>
		
	</div>
	<div class="actions-container">
		<div class="action-type">
			<div class="action post-action"> 
				<h4>Posts</h4>
			</div>
			<div class="action comment-action">
				<h4>Comments</h4>
			</div>
			<div class="action mention-action">
				<h4>Mentions</h4>
			</div>
			<div class="action like-action">
				<h4>Likes</h4>
			</div>
		</div>
	</div>
	<div class="status-container">
		<div class='get-posts'>

			<?php
			
			// // get users posts
			// $sql = "SELECT * FROM posts WHERE user_id = ? AND parent_id is NULL";
			// $params = array($_GET["id"]);
			// $rows = $db->fetch($sql, $params);
			// echo count((array)$rows) == 0 ? "No posts" : null;
			
			// include $appIncludes."feeds.php"; ?>
		</div>
		<div class='get-comments show-action'>

			<?php
			
			// get users comments
			$sql = "SELECT * FROM posts WHERE user_id = ? AND parent_id is not NULL";
			$params = array($_GET["id"]);
			$rows = $db->fetch($sql, $params);
			echo count((array)$rows) == 0 ? "No comments" : null;
			
			foreach($rows as $index){
				$sql = "SELECT * FROM posts WHERE id = ?";
				$params = array($index->parent_id);
				$rows = $db->fetch($sql, $params);

				include $appIncludes."feeds.php";
			}?>
			
		</div>

		<div class='get-mentions show-action'>

			<?php
			
			// get users mentions
			$sql = "SELECT * FROM posts_mentions WHERE user_id = ?";
			$params = array($_GET["id"]);
			$rows = $db->fetch($sql, $params);
			echo count((array)$rows) == 0 ? "No mentions" : null;
			
			foreach($rows as $index){
				$sql = "SELECT * FROM posts WHERE id = ?";
				$params = array($index->post_id);
				$rows = $db->fetch($sql, $params);

				include $appIncludes."feeds.php";
			}?>
			
		</div>
		<div class='get-likes show-action'>

			<?php
			
			// get users likes
			$sql = "SELECT * FROM posts_likes WHERE user_id = ?";
			$params = array($_GET["id"]);
			$rows = $db->fetch($sql, $params);
			echo count((array)$rows) == 0 ? "No likes" : null;
			
			foreach($rows as $index){
				$sql = "SELECT * FROM posts WHERE id = ?";
				$params = array($index->post_id);
				$rows = $db->fetch($sql, $params);
				
				include $appIncludes."feeds.php";
			}?>
			
		</div>
		

	</div>
	<div id="loading-container">
		<button id="load-posts">more...</button>
		<div id="loader">
			<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: transparent; display: block; shape-rendering: auto;" width="80px"  height="80px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
				<circle cx="50" cy="50" r="32" stroke-width="5" stroke="#e4560fe8" stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round">
					<animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="2s" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
				</circle>
			</svg><!--[ldio] generated by https://loading.io/ -->
		</div>
	</div>
</div>

<?php require_once $appIncludes."footer.php" ?>